config/routes.rb
  Rails.application.routes.draw do
  resources :phases
  get 'home/index'
  resources :sub_tasks
  resources :comments
    resources :projects do
      resources :tasks  
    end
    devise_for :users
    root to: "home#index"
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/task.rb
class Task < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :sub_tasks, dependent: :destroy
  belongs_to :project
  belongs_to :user
  belongs_to :phase
  validates :title, :description, :due_date, :end_date, :priority, :story_point, :start_date, :status, :task_type, presence: :true
  #file upload
  has_many_attached :attached_files
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1
  def show
    @comments = @task.comments
    @sub_tasks = @task.sub_tasks
    @comment = Comment.new
    @sub_task = SubTask.new
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to(project_path(@project), notice: 'Task was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update(task_params)
      redirect_to([@task.project, @task], notice: 'Task was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @task.destroy

    redirect_to project_path(@project)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:title, :phase_id, :description, :due_date, :end_date, :start_date, :story_point, :status, :task_type,  :project_id, :priority, :user_id, attached_files:[])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class='custom-form'>
<%= form_for([@task.project, @task])  do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h3>Add Task</h3>
  <div class="field">
    <%= f.label :title , class:'form-label' %><br />
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :description ,class:'form-label' %><br />
    <%= f.text_area :description , class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :due_date ,class:'form-label' %><br />
    <%= f.date_select :due_date , class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :end_date, class:'form-label'  %><br />
    <%= f.date_select :end_date , class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :start_date, class:'form-label' %><br />
    <%= f.date_select :start_date, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :story_point, class:'form-label' %><br />
    <%= f.number_field :story_point, step: 0.000000000000000001 , class: 'form-control'%>
  </div>
    <div class="field">
    <%= f.label :priority, class:'form-label' %><br />
    <%= f.select :priority , options_for_select(["Low", "Medium", "High", "Urgent"]) , class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :status, class:'form-label' %><br />
    <%= f.select :status, options_for_select(["In Progress", "On Hold","Completed"]) , class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :phase_id, class:'form-label' %><br />
    <%= f.collection_select :phase_id, Phase.all, :id, :title , class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :task_type, class:'form-label' %><br />
    <%= f.text_field :task_type , class: 'form-control'%>
  </div>
  <div class="field">
  <%= f.label :attached_files, class:'form-label' %>
  <%= f.file_field :attached_files, multiple: true, class: 'form-control' %>
  </div>
 <div class="field">
    <%= f.number_field :project_id,id:  :task_project_id, value: @project.id, type: :hidden%>
  </div>
   <div class="field">
    <%= f.number_field :user_id, id: :task_user_id,  value: current_user.id, type: :hidden %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-outline-success centr_button'%>
  </div>
<% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class='project_show'>

<div class='card'>
<div class='card-body'>
<div class='card-title'>
  <%= @task.title %>
</div>
<div class='card-text'>
<p>
  <b>Description:</b>
  <%= @task.description %>
</p>
<p>
  <b>Due date:</b>
  <%= @task.due_date %>
</p>
<p>
  <b>End date:</b>
  <%= @task.end_date %>
</p>
<p>
  <b>Start date:</b>
  <%= @task.start_date %>
</p>
<p>
  <b>Story point:</b>
  <%= @task.story_point %>
</p>
<p>
  <b>Task type:</b>
  <%= @task.task_type %>
</p>
<p>
<span class="badge alert-info">
   <b>Priority:</b>
 <%= @task.priority %>
</span>
<p>

<span class="badge alert-info">
  <b>Status</b>
  <%= @task.status %>
</span>

<div>
<b>Attachments</b>
<% @task.attached_files.each do |a| %>
<p><a href=<%= rails_blob_path(a)%> target='blank'><%=a.filename%></a>
<%end%>

</div>

</div>
</div>
<div class='card-footer'>
<%= link_to 'Edit', edit_project_task_path(@task.project, @task),class: 'btn btn-primary'  %> |
<%= link_to 'Delete',[@task.project, @task], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
</div>
</div>


<hr/>

<div>
      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="pills-subtasks-tab" data-bs-toggle="pill" data-bs-target="#pills-subtasks" type="button" role="tab" aria-controls="pills-subtasks" aria-selected="true">SubTasks</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-comments-tab" data-bs-toggle="pill" data-bs-target="#pills-comments" type="button" role="tab" aria-controls="pills-comments" aria-selected="false">Comments</button>
        </li>
      </ul>
          <hr/>

      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-subtasks" role="tabpanel" aria-labelledby="pills-subtasks-tab">
          <div class='custom-form'>
<%= form_for(@sub_task) do |form| %>
  <% if @sub_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_task.errors.count, "error") %> prohibited this sub_task from being saved:</h2>

      <ul>
        <% @sub_task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title , class:'form-label'%>
    <%= form.text_field :title , class:'form-control'%>
  </div>

  <div class="field">
    <%= form.label :status , class:'form-label'%>
    <%= form.select :status, options_for_select(["In Progress", "On Hold","Completed"]) , class:'form-control'%>
  </div>


<div class="field">
    <%= form.number_field :task_id, value: @task.id, type: :hidden %>
  </div>


  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-outline-success centr_button'%>
  </div>
<% end %>

</div>
<hr/>      

<% if @sub_tasks.count != 0%>
<div class='card_container container'>
    <% @sub_tasks.each do |sub_task| %>
      <div class='col-xl-3 col-md-4'>
        <p><%= sub_task.title %></p>
        <span class="badge alert-info">
          <%=sub_task.status %>
        </span><br/>
        <%= link_to 'Edit', edit_sub_task_path(sub_task), class: 'btn btn-primary' %>
   <%= link_to 'Destroy', sub_task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </div>
    <% end %>
    </div>
<%else %>
<p class='nothing-here'>No SubTasks Yet!</p>

<%end%>
        </div>

        <div class="tab-pane fade" id="pills-comments" role="tabpanel" aria-labelledby="pills-comments-tab">
        <table>
  <tbody>
  <% if @comments.count !=0 %>
    <% @comments.each do |comment| %>
      <div class='comment-container container'>
        <i><%= comment.body %></i>
        <div>
        <td><%= link_to 'Edit', edit_comment_path(comment) , class: 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn btn-danger' %></td>
        </div>
      </div>
    <% end %>
    <% else %>
    <p class='nothing-here'>No Comments Yet!</p>
    <% end %>
  </tbody>
</table>

<hr/>
        <div class='custom-form'>
<%= form_for(@comment) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body , class:'form-label'%>
    <%= form.text_field :body, class:'form-control' %>
  </div>

<div class="field">
    <%= form.number_field :task_id, value: @task.id, type: :hidden %>
  </div>
   <div class="field">
    <%= form.number_field :user_id, id: :task_user_id,  value: current_user.id, type: :hidden%>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-outline-success centr_button'%>
  </div>
<% end %>
</div>
</div>
</div>
</div>
</div>