config/routes.rb
  Rails.application.routes.draw do
  resources :phases
  get 'home/index'
  resources :sub_tasks
  resources :comments
    resources :projects do
      resources :tasks  
    end
    devise_for :users
    root to: "home#index"
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user 
  validates :title, :description, :status,:due_date ,presence: :true
  validates_length_of :title, minimum: 5, maximum: 255
  validates_length_of :description, minimum: 5, maximum: 1000
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = current_user.projects
    @projects_on_hold = @projects.where(status: 'On Hold')
    @projects_in_progress = @projects.where(status: 'In Progress')
    @projects_completed = @projects.where(status: 'Completed')

  end

  # GET /projects/1 or /projects/1.json
  def show
    @task = @project.tasks.build
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description, :status, :due_date)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class='custom-form'>
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class:'form-label' %>
    <%= form.text_field :title, class:'form-control'%>
  </div>

  <div class="field">
    <%= form.label :description, class:'form-label'%>
    <%= form.text_area :description, class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :status,  class:'form-label' %>
    <%= form.select :status, options_for_select(["In Progress", "On Hold","Completed"]) %>
  </div>

  <div class="field">
    <%= form.label :due_date,  class:'form-label'%>
    <%= form.date_select :due_date, class:'form-control'%>
  </div>
  
  <div class="actions", >
    <%= form.submit "Submit", class: 'btn btn-outline-success centr_button'%>
  </div>
<% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project,  class:'btn btn-outline-secondary' %> 
<%= link_to 'Back', projects_path, class:'btn btn-outline-info' %>

app/views/projects/index.html.erb
<div class='projects_index'>
<h1>PROJECTS <span class='count'><%= @projects.count %></span></h1>

<%= link_to 'Add Project', new_project_path, class:'btn btn-outline-danger' %>

<%if @projects.count !=0 %>
<div class='row'>
<div class= 'col'>
<h5>On Hold <span class='count'><%= @projects_on_hold.length %></span></h5>
<% @projects_on_hold.each do |p| %>
<div class='project_view'>
<p><%= p.title %></p>
<%= link_to 'View >', p%>
</div>
<% end %>
</div>
<div class= 'col'>
<h5>In Progress <span class='count'><%= @projects_in_progress.length %></span></h5>
<% @projects_in_progress.each do |p| %>
<div class='project_view'>
<p><%= p.title %></p>
<%= link_to 'View >', p%>
</div>
<% end %>
</div>
<div class= 'col'>
<h5>Completed <span class='count'><%= @projects_completed.length %></span></h5>
<% @projects_completed.each do |p| %>
<div class='project_view'>
<p><%= p.title %></p>
<%= link_to 'View >', p%>
</div>
<% end %>
</div>
</div>
<% else %>
<p class='nothing-here'>No Projects Yet!<p>
<% end %>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path, class:'btn btn-outline-info' %>

app/views/projects/show.html.erb
<div class='project_show'>
<div class='card'>


<div class='card-body'>
<div class='card-title'>
  <%= @project.title %>
</div>
<div class='card-text'>
<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<span class="badge alert-info">
  <%= @project.status %>
</span>

<p>
  <strong>Due date:</strong>
  <%= @project.due_date %>
</p>
</div>
</div>
<div class='card-footer'>

<%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-primary' %> 
<%= link_to 'Delete', @project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'%>
</div>
</div>


<hr/>


<h3>Tasks</h3>
<% if @project.tasks.count != 0 %>
<div class='card_container container'>
<% @project.tasks.each do |task| %>
<% if task.persisted? %>
  <div class='col-xl-2 col-md-4'>
    <p><%= task.title %></p>
    <p><%= link_to 'View >', [task.project, task] %></p>
  </div>
<% end%>
<% end %>
</div>
<% else %>
<p class='nothing-here'>No Tasks Yet!</p>
<% end %>


<hr/>

<div class='custom-form'>
<%= form_for([@task.project, @task])  do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h3>Add Task</h3>
  <div class="field">
    <%= f.label :title , class:'form-label' %><br />
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :description ,class:'form-label' %><br />
    <%= f.text_area :description , class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :due_date ,class:'form-label' %><br />
    <%= f.date_select :due_date , class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :end_date, class:'form-label'  %><br />
    <%= f.date_select :end_date , class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :start_date, class:'form-label' %><br />
    <%= f.date_select :start_date, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :story_point, class:'form-label' %><br />
    <%= f.number_field :story_point, step: 0.000000000000000001 , class: 'form-control'%>
  </div>
    <div class="field">
    <%= f.label :priority, class:'form-label' %><br />
    <%= f.select :priority , options_for_select(["Low", "Medium", "High", "Urgent"]) , class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :status, class:'form-label' %><br />
    <%= f.select :status, options_for_select(["In Progress", "On Hold","Completed"]) , class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :phase_id, class:'form-label' %><br />
    <%= f.collection_select :phase_id, Phase.all, :id, :title , class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :task_type, class:'form-label' %><br />
    <%= f.text_field :task_type , class: 'form-control'%>
  </div>
  <div class="field">
  <%= f.label :attached_files, class:'form-label' %>
  <%= f.file_field :attached_files, multiple: true, class: 'form-control' %>
  </div>
 <div class="field">
    <%= f.number_field :project_id,id:  :task_project_id, value: @project.id, type: :hidden%>
  </div>
   <div class="field">
    <%= f.number_field :user_id, id: :task_user_id,  value: current_user.id, type: :hidden %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-outline-success centr_button'%>
  </div>
<% end %>
</div>
</div>