config/routes.rb
  Rails.application.routes.draw do
  resources :phases
  get 'home/index'
  resources :sub_tasks
  resources :comments
    resources :projects do
      resources :tasks  
    end
    devise_for :users
    root to: "home#index"
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/controllers/phases_controller.rb
class PhasesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_phase, only: %i[ show edit update destroy ]

  # GET /phases or /phases.json
  def index
    @phases = Phase.all
  end

  # GET /phases/1 or /phases/1.json
  def show
  end

  # GET /phases/new
  def new
    @phase = Phase.new
  end

  # GET /phases/1/edit
  def edit
  end

  # POST /phases or /phases.json
  def create
    @phase = Phase.new(phase_params)

    respond_to do |format|
      if @phase.save
        format.html { redirect_to @phase, notice: "Phase was successfully created." }
        format.json { render :show, status: :created, location: @phase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phases/1 or /phases/1.json
  def update
    respond_to do |format|
      if @phase.update(phase_params)
        format.html { redirect_to @phase, notice: "Phase was successfully updated." }
        format.json { render :show, status: :ok, location: @phase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phases/1 or /phases/1.json
  def destroy
    @phase.destroy
    respond_to do |format|
      format.html { redirect_to phases_url, notice: "Phase was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phase
      @phase = Phase.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phase_params
      params.require(:phase).permit(:title)
    end
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/views/phases/_form.html.erb
<div class='custom-form'>
<%= form_with(model: phase) do |form| %>
  <% if phase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phase.errors.count, "error") %> prohibited this phase from being saved:</h2>

      <ul>
        <% phase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title , class: 'form-label'%>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-outline-success centr_button'%>
  </div>
<% end %>
</div>

app/views/phases/edit.html.erb
<h1>Editing Phase</h1>

<%= render 'form', phase: @phase %>

<%= link_to 'Show', @phase, class:'btn btn-outline-secondary' %> 
<%= link_to 'Back', phases_path, class:'btn btn-outline-info' %>

app/views/phases/index.html.erb
<h1>Phases</h1>

<table class='table table-striped'>
  <thead class='thead-dark'>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phases.each do |phase| %>
      <tr>
        <td><%= phase.title %></td>
        <td><%= link_to 'Edit', edit_phase_path(phase), class: 'btn btn-danger' %></td>
        <td><%= link_to 'Destroy', phase, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-success' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phase', new_phase_path, class: 'btn btn-outline-success' %>

app/views/phases/new.html.erb
<h1>New Phase</h1>

<%= render 'form', phase: @phase %>

<%= link_to 'Back', phases_path, class:'btn btn-outline-info' %>